# Generated by Django 4.2.13 on 2024-05-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flowrate_units', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.design')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_unit', to='data.unit')),
                ('to_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_unit', to='data.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flowrate', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('parent_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.stream')),
            ],
        ),
    ]
